/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server;

import java.net.*; 
import java.io.*;
import java.util.*;
import javax.swing.JOptionPane;


/**
 *
 * @author nunos
 */
public class ServerClientLogin extends javax.swing.JFrame {

    final List<WeatherStation> StationList;
    final List<Integer> ConnectedFarmerClients;
    /**
     * Creates new form ServerClientLogin
     */
    public ServerClientLogin(List<WeatherStation> StationList, List<Integer> ConnectedFarmerClients) {
        this.StationList = StationList;
        this.ConnectedFarmerClients = ConnectedFarmerClients;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        TXTUsername = new javax.swing.JTextField();
        BTNSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TXTPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Server Login");

        panel1.setForeground(new java.awt.Color(204, 204, 204));
        panel1.setName("PNLLogin"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Password:");
        jLabel2.setName("LBLPassword"); // NOI18N

        TXTUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTUsername.setToolTipText("");
        TXTUsername.setName("TXTUsername"); // NOI18N

        BTNSubmit.setBackground(new java.awt.Color(0, 153, 0));
        BTNSubmit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNSubmit.setForeground(java.awt.Color.white);
        BTNSubmit.setText("Submit");
        BTNSubmit.setName("BTNSubmit"); // NOI18N
        BTNSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNSubmitMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BTNSubmitMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Username:");
        jLabel3.setName("LBLUsername"); // NOI18N

        TXTPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TXTUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(TXTPassword)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(BTNSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXTUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXTPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(BTNSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNSubmitMouseClicked

    }//GEN-LAST:event_BTNSubmitMouseClicked

    private void BTNSubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNSubmitMousePressed
        String username = this.TXTUsername.getText();
        String password = this.TXTPassword.getText();
        
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please insert a username and password.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        try {
            int userId = FileHandler.getInstance().verifyLoginCredentials(username, password, true);
            
            if (userId == -1) {
                JOptionPane.showMessageDialog(this, "Incorrect details, please verify if you inserted the correct details.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (userId == -2) {
                JOptionPane.showMessageDialog(this, "Your account isn't active. Please contact a server administrator.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            this.TXTUsername.setText("");
            this.TXTPassword.setText("");
            JOptionPane.showMessageDialog(this, "Welcome back, " + username + "!", "Success!", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            ServerClientMainWindow mainW = new ServerClientMainWindow(this, userId, this.StationList, this.ConnectedFarmerClients);
            mainW.setVisible(true);
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "An error occured, please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTNSubmitMousePressed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
/
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerClientLogin().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNSubmit;
    private javax.swing.JPasswordField TXTPassword;
    private javax.swing.JTextField TXTUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
