/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server;


import java.awt.Panel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.JOptionPane;

import javax.swing.JButton;
import javax.swing.JPanel;

import javax.swing.AbstractAction;
import javax.swing.Action;
import java.awt.event.ActionEvent;

import java.util.*;

/**
 *
 * @author nunos
 */
public class Server_Menu_WeatherStations extends javax.swing.JPanel {

    /**
     * Creates new form Server_Menu_WeatherStations
     */

    public Server_Menu_WeatherStations() {
        initComponents();
        this.PNLWeatherStationEdit.setVisible(false);
        updateWeatherStations();
    }
    
    TreeMap<Integer, List<String>> weatherStations = new java.util.TreeMap<Integer, List<String>>();
    
    private void updateWeatherStations() {
        this.weatherStations = FileHandler.getInstance().getAllWeatherStations();
        DefaultTableModel model = (DefaultTableModel) this.TBLWeatherStations.getModel();
        model.setNumRows(0);
        for (Map.Entry<Integer, List<String>> weatherStation : this.weatherStations.entrySet()) {
            String activate = (weatherStation.getValue().get(1).equals("1")) ? "ACTIVATE" : "DEACTIVATE";
            model.addRow(new Object[]{weatherStation.getValue().get(0), weatherStation.getValue().get(2), 
                weatherStation.getValue().get(3), weatherStation.getValue().get(4), activate, "Edit"});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TBLWeatherStations = new javax.swing.JTable();
        PNLWeatherStationEdit = new java.awt.Panel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        TXTGPSLocation = new javax.swing.JTextField();
        TXTUserFor = new javax.swing.JTextField();
        TXTWeatherStationId = new javax.swing.JTextField();
        TXTHectares = new javax.swing.JTextField();
        BTNDelete = new javax.swing.JButton();
        BTNUpdate1 = new javax.swing.JButton();

        TBLWeatherStations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "WeatherStationId", "GPS Location", "Hectares"
                , "Used for", "Activate", "Edit"
            }
        ));
        TBLWeatherStations.setEnabled(false);
        TBLWeatherStations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLWeatherStationsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBLWeatherStations);

        label1.setText("GPS Location");

        label2.setText("Hectares");

        label3.setText("Used For");

        label4.setText("WeatherStationId");

        TXTWeatherStationId.setEnabled(false);

        BTNDelete.setText("Delete Weather Station");
        BTNDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNDeleteMouseClicked(evt);
            }
        });
        BTNDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDeleteActionPerformed(evt);
            }
        });

        BTNUpdate1.setText("Update");
        BTNUpdate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNUpdate1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PNLWeatherStationEditLayout = new javax.swing.GroupLayout(PNLWeatherStationEdit);
        PNLWeatherStationEdit.setLayout(PNLWeatherStationEditLayout);
        PNLWeatherStationEditLayout.setHorizontalGroup(
            PNLWeatherStationEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLWeatherStationEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLWeatherStationEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLWeatherStationEditLayout.createSequentialGroup()
                        .addComponent(BTNDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLWeatherStationEditLayout.createSequentialGroup()
                        .addGroup(PNLWeatherStationEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PNLWeatherStationEditLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(PNLWeatherStationEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PNLWeatherStationEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTHectares, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTGPSLocation)
                                    .addComponent(TXTUserFor)))
                            .addGroup(PNLWeatherStationEditLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(TXTWeatherStationId, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))))
        );
        PNLWeatherStationEditLayout.setVerticalGroup(
            PNLWeatherStationEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLWeatherStationEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLWeatherStationEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTWeatherStationId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(PNLWeatherStationEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNLWeatherStationEditLayout.createSequentialGroup()
                        .addComponent(TXTGPSLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(TXTHectares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PNLWeatherStationEditLayout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(PNLWeatherStationEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTUserFor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(PNLWeatherStationEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addComponent(PNLWeatherStationEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PNLWeatherStationEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TBLWeatherStationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLWeatherStationsMouseClicked
        JTable tableSource = (JTable)evt.getSource();
        int row = tableSource.rowAtPoint(evt.getPoint());
        int column = tableSource.columnAtPoint(evt.getPoint());

        int weatherStationId = -1;
        switch (column) {
            case 4:
                weatherStationId = Integer.parseInt((String)tableSource.getModel().getValueAt(row, 0));
                String action = (String)tableSource.getModel().getValueAt(row, 4);
                activateWeatherStation(weatherStationId, (action != "ACTIVATE"));
                break;
            case 5:
                PNLWeatherStationEdit.setVisible(true);
                this.validate();
                weatherStationId = Integer.parseInt((String)tableSource.getModel().getValueAt(row, 0));
                updatePNLUserData(weatherStationId);
                break;
            default:
                PNLWeatherStationEdit.setVisible(false);
                this.validate();
                break;
        }

        // JOptionPane.showMessageDialog(null, s + " " + (column==3));
    }//GEN-LAST:event_TBLWeatherStationsMouseClicked
    private void activateWeatherStation(int weatherStationId, boolean action) {
        FileHandler.getInstance().changeWeatherStationActiveStatus(weatherStationId, action);
        updateWeatherStations();
    }
    
    private void updatePNLUserData(int weatherStationId) {
        List<String> currentWeatherStation = weatherStations.get(weatherStationId);
        this.TXTWeatherStationId.setText(currentWeatherStation.get(0));
        this.TXTGPSLocation.setText(currentWeatherStation.get(2));
        this.TXTHectares.setText(currentWeatherStation.get(3));
        this.TXTUserFor.setText(currentWeatherStation.get(4));
    }
    private void BTNDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNDeleteMouseClicked
        deleteCurrentWeatherStation();
    }//GEN-LAST:event_BTNDeleteMouseClicked

    private void deleteCurrentWeatherStation() {
        
    }
        
    private void BTNDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNDeleteActionPerformed

    private void BTNUpdate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNUpdate1MouseClicked
        updateCurrentWeatherStationData();
    }//GEN-LAST:event_BTNUpdate1MouseClicked

    private void updateCurrentWeatherStationData() {
        int weatherStationId = Integer.parseInt(this.TXTWeatherStationId.getText());
        String GPSLocation = this.TXTGPSLocation.getText();
        String hectares = this.TXTHectares.getText();
        String userFor = this.TXTUserFor.getText();
        
        if (GPSLocation.isEmpty() || hectares.isEmpty() || userFor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please don't leave any field empty.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        FileHandler.getInstance().updateWeatherStationDate(weatherStationId, GPSLocation, hectares, userFor);
        updateWeatherStations();
        JOptionPane.showMessageDialog(this, "User data sucessfully updated!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNDelete;
    private javax.swing.JButton BTNUpdate1;
    private java.awt.Panel PNLWeatherStationEdit;
    private javax.swing.JTable TBLWeatherStations;
    private javax.swing.JTextField TXTGPSLocation;
    private javax.swing.JTextField TXTHectares;
    private javax.swing.JTextField TXTUserFor;
    private javax.swing.JTextField TXTWeatherStationId;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables
}
